// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: analytics.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countActiveSubscriptions = `-- name: CountActiveSubscriptions :one
SELECT count(*) FROM subscriptions WHERE status = 'active'
`

func (q *Queries) CountActiveSubscriptions(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveSubscriptions)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countFailedInvoices = `-- name: CountFailedInvoices :one
SELECT count(*) FROM invoices WHERE status = 'uncollectible'
`

func (q *Queries) CountFailedInvoices(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countFailedInvoices)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPaymentsToday = `-- name: CountPaymentsToday :one
SELECT count(*) FROM invoices
WHERE status = 'paid' AND issued_at >= date_trunc('day', now())
`

func (q *Queries) CountPaymentsToday(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countPaymentsToday)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const revenueSeries = `-- name: RevenueSeries :many
SELECT date_trunc('day', issued_at)::date AS day, COALESCE(SUM(amount), 0)::bigint AS amount
FROM invoices
WHERE status = 'paid' AND issued_at >= now() - interval '30 days'
GROUP BY day
ORDER BY day
`

type RevenueSeriesRow struct {
	Day    pgtype.Date `json:"day"`
	Amount int64       `json:"amount"`
}

func (q *Queries) RevenueSeries(ctx context.Context) ([]RevenueSeriesRow, error) {
	rows, err := q.db.Query(ctx, revenueSeries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RevenueSeriesRow
	for rows.Next() {
		var i RevenueSeriesRow
		if err := rows.Scan(&i.Day, &i.Amount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumMRR = `-- name: SumMRR :one
SELECT COALESCE(SUM(
    CASE WHEN p.interval = 'year' THEN p.amount / 12 ELSE p.amount END
), 0)::bigint AS mrr
FROM subscriptions s
JOIN plans p ON p.id = s.plan_id
WHERE s.status = 'active'
`

// Monthly recurring revenue: normalize yearly plans to a monthly figure (minor units).
func (q *Queries) SumMRR(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, sumMRR)
	var mrr int64
	err := row.Scan(&mrr)
	return mrr, err
}
