// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: customers.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createCustomer = `-- name: CreateCustomer :one
INSERT INTO customers (tenant_id, name, email)
VALUES ($1, $2, $3)
RETURNING id, tenant_id, email, name, nomba_token_key, nomba_virtual_account, created_at, updated_at
`

type CreateCustomerParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	Name     *string   `json:"name"`
	Email    string    `json:"email"`
}

func (q *Queries) CreateCustomer(ctx context.Context, arg CreateCustomerParams) (Customer, error) {
	row := q.db.QueryRow(ctx, createCustomer, arg.TenantID, arg.Name, arg.Email)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Email,
		&i.Name,
		&i.NombaTokenKey,
		&i.NombaVirtualAccount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCustomer = `-- name: GetCustomer :one
SELECT id, tenant_id, email, name, nomba_token_key, nomba_virtual_account, created_at, updated_at FROM customers WHERE id = $1
`

func (q *Queries) GetCustomer(ctx context.Context, id uuid.UUID) (Customer, error) {
	row := q.db.QueryRow(ctx, getCustomer, id)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Email,
		&i.Name,
		&i.NombaTokenKey,
		&i.NombaVirtualAccount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCustomerByEmail = `-- name: GetCustomerByEmail :one
SELECT id, tenant_id, email, name, nomba_token_key, nomba_virtual_account, created_at, updated_at FROM customers WHERE email = $1
`

func (q *Queries) GetCustomerByEmail(ctx context.Context, email string) (Customer, error) {
	row := q.db.QueryRow(ctx, getCustomerByEmail, email)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Email,
		&i.Name,
		&i.NombaTokenKey,
		&i.NombaVirtualAccount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCustomers = `-- name: ListCustomers :many
SELECT id, tenant_id, email, name, nomba_token_key, nomba_virtual_account, created_at, updated_at FROM customers
WHERE ($1::text IS NULL
       OR name ILIKE '%' || $1 || '%'
       OR email ILIKE '%' || $1 || '%')
ORDER BY created_at DESC
LIMIT $2
`

type ListCustomersParams struct {
	Q   *string `json:"q"`
	Lim int32   `json:"lim"`
}

func (q *Queries) ListCustomers(ctx context.Context, arg ListCustomersParams) ([]Customer, error) {
	rows, err := q.db.Query(ctx, listCustomers, arg.Q, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Customer
	for rows.Next() {
		var i Customer
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Email,
			&i.Name,
			&i.NombaTokenKey,
			&i.NombaVirtualAccount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setCustomerCardToken = `-- name: SetCustomerCardToken :one
UPDATE customers SET nomba_token_key = $2 WHERE id = $1 RETURNING id, tenant_id, email, name, nomba_token_key, nomba_virtual_account, created_at, updated_at
`

type SetCustomerCardTokenParams struct {
	ID            uuid.UUID `json:"id"`
	NombaTokenKey *string   `json:"nomba_token_key"`
}

func (q *Queries) SetCustomerCardToken(ctx context.Context, arg SetCustomerCardTokenParams) (Customer, error) {
	row := q.db.QueryRow(ctx, setCustomerCardToken, arg.ID, arg.NombaTokenKey)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Email,
		&i.Name,
		&i.NombaTokenKey,
		&i.NombaVirtualAccount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCustomer = `-- name: UpdateCustomer :one
UPDATE customers SET
    name  = COALESCE($1, name),
    email = COALESCE($2, email)
WHERE id = $3
RETURNING id, tenant_id, email, name, nomba_token_key, nomba_virtual_account, created_at, updated_at
`

type UpdateCustomerParams struct {
	Name  *string   `json:"name"`
	Email *string   `json:"email"`
	ID    uuid.UUID `json:"id"`
}

func (q *Queries) UpdateCustomer(ctx context.Context, arg UpdateCustomerParams) (Customer, error) {
	row := q.db.QueryRow(ctx, updateCustomer, arg.Name, arg.Email, arg.ID)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Email,
		&i.Name,
		&i.NombaTokenKey,
		&i.NombaVirtualAccount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
