// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: invoices.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const getInvoice = `-- name: GetInvoice :one
SELECT id, tenant_id, subscription_id, customer_id, amount, currency, status, period_start, period_end, nomba_reference, issued_at, created_at FROM invoices WHERE id = $1
`

func (q *Queries) GetInvoice(ctx context.Context, id uuid.UUID) (Invoice, error) {
	row := q.db.QueryRow(ctx, getInvoice, id)
	var i Invoice
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SubscriptionID,
		&i.CustomerID,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.NombaReference,
		&i.IssuedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listInvoiceItems = `-- name: ListInvoiceItems :many
SELECT id, tenant_id, invoice_id, description, amount, quantity, period_start, period_end, created_at FROM invoice_items WHERE invoice_id = $1 ORDER BY created_at
`

func (q *Queries) ListInvoiceItems(ctx context.Context, invoiceID uuid.UUID) ([]InvoiceItem, error) {
	rows, err := q.db.Query(ctx, listInvoiceItems, invoiceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []InvoiceItem
	for rows.Next() {
		var i InvoiceItem
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.InvoiceID,
			&i.Description,
			&i.Amount,
			&i.Quantity,
			&i.PeriodStart,
			&i.PeriodEnd,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInvoicesByCustomer = `-- name: ListInvoicesByCustomer :many
SELECT id, tenant_id, subscription_id, customer_id, amount, currency, status, period_start, period_end, nomba_reference, issued_at, created_at FROM invoices
WHERE customer_id = $1
ORDER BY issued_at DESC
`

func (q *Queries) ListInvoicesByCustomer(ctx context.Context, customerID uuid.UUID) ([]Invoice, error) {
	rows, err := q.db.Query(ctx, listInvoicesByCustomer, customerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Invoice
	for rows.Next() {
		var i Invoice
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.SubscriptionID,
			&i.CustomerID,
			&i.Amount,
			&i.Currency,
			&i.Status,
			&i.PeriodStart,
			&i.PeriodEnd,
			&i.NombaReference,
			&i.IssuedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
