// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Customer struct {
	ID                  uuid.UUID `json:"id"`
	TenantID            uuid.UUID `json:"tenant_id"`
	Email               string    `json:"email"`
	Name                *string   `json:"name"`
	NombaTokenKey       *string   `json:"nomba_token_key"`
	NombaVirtualAccount *string   `json:"nomba_virtual_account"`
	CreatedAt           time.Time `json:"created_at"`
	UpdatedAt           time.Time `json:"updated_at"`
}

type Invoice struct {
	ID             uuid.UUID          `json:"id"`
	TenantID       uuid.UUID          `json:"tenant_id"`
	SubscriptionID pgtype.UUID        `json:"subscription_id"`
	CustomerID     uuid.UUID          `json:"customer_id"`
	Amount         int64              `json:"amount"`
	Currency       string             `json:"currency"`
	Status         string             `json:"status"`
	PeriodStart    pgtype.Timestamptz `json:"period_start"`
	PeriodEnd      pgtype.Timestamptz `json:"period_end"`
	NombaReference *string            `json:"nomba_reference"`
	IssuedAt       time.Time          `json:"issued_at"`
	CreatedAt      time.Time          `json:"created_at"`
}

type InvoiceItem struct {
	ID          uuid.UUID          `json:"id"`
	TenantID    uuid.UUID          `json:"tenant_id"`
	InvoiceID   uuid.UUID          `json:"invoice_id"`
	Description string             `json:"description"`
	Amount      int64              `json:"amount"`
	Quantity    int32              `json:"quantity"`
	PeriodStart pgtype.Timestamptz `json:"period_start"`
	PeriodEnd   pgtype.Timestamptz `json:"period_end"`
	CreatedAt   time.Time          `json:"created_at"`
}

type Plan struct {
	ID        uuid.UUID          `json:"id"`
	TenantID  uuid.UUID          `json:"tenant_id"`
	Name      string             `json:"name"`
	Amount    int64              `json:"amount"`
	Currency  string             `json:"currency"`
	Interval  string             `json:"interval"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
	CreatedAt time.Time          `json:"created_at"`
	UpdatedAt time.Time          `json:"updated_at"`
}

type ProcessedEvent struct {
	RequestID   string             `json:"request_id"`
	Consumer    string             `json:"consumer"`
	Status      string             `json:"status"`
	Result      []byte             `json:"result"`
	CreatedAt   time.Time          `json:"created_at"`
	ProcessedAt pgtype.Timestamptz `json:"processed_at"`
}

type Subscription struct {
	ID                 uuid.UUID          `json:"id"`
	TenantID           uuid.UUID          `json:"tenant_id"`
	CustomerID         uuid.UUID          `json:"customer_id"`
	PlanID             uuid.UUID          `json:"plan_id"`
	Status             string             `json:"status"`
	CurrentPeriodStart pgtype.Timestamptz `json:"current_period_start"`
	CurrentPeriodEnd   pgtype.Timestamptz `json:"current_period_end"`
	CancelAtPeriodEnd  bool               `json:"cancel_at_period_end"`
	CanceledAt         pgtype.Timestamptz `json:"canceled_at"`
	CreatedAt          time.Time          `json:"created_at"`
	UpdatedAt          time.Time          `json:"updated_at"`
}

type Tenant struct {
	ID                uuid.UUID `json:"id"`
	Name              string    `json:"name"`
	Email             string    `json:"email"`
	NombaAccountID    *string   `json:"nomba_account_id"`
	NombaClientID     *string   `json:"nomba_client_id"`
	NombaClientSecret *string   `json:"nomba_client_secret"`
	ApiKeyHash        *string   `json:"api_key_hash"`
	CreatedAt         time.Time `json:"created_at"`
	UpdatedAt         time.Time `json:"updated_at"`
}
