// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: plans.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createPlan = `-- name: CreatePlan :one
INSERT INTO plans (tenant_id, name, amount, currency, interval)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, tenant_id, name, amount, currency, interval, deleted_at, created_at, updated_at
`

type CreatePlanParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	Name     string    `json:"name"`
	Amount   int64     `json:"amount"`
	Currency string    `json:"currency"`
	Interval string    `json:"interval"`
}

func (q *Queries) CreatePlan(ctx context.Context, arg CreatePlanParams) (Plan, error) {
	row := q.db.QueryRow(ctx, createPlan,
		arg.TenantID,
		arg.Name,
		arg.Amount,
		arg.Currency,
		arg.Interval,
	)
	var i Plan
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Amount,
		&i.Currency,
		&i.Interval,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPlan = `-- name: GetPlan :one
SELECT id, tenant_id, name, amount, currency, interval, deleted_at, created_at, updated_at FROM plans WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetPlan(ctx context.Context, id uuid.UUID) (Plan, error) {
	row := q.db.QueryRow(ctx, getPlan, id)
	var i Plan
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Amount,
		&i.Currency,
		&i.Interval,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPlans = `-- name: ListPlans :many
SELECT id, tenant_id, name, amount, currency, interval, deleted_at, created_at, updated_at FROM plans
WHERE ($1::bool OR deleted_at IS NULL)
ORDER BY created_at DESC
`

func (q *Queries) ListPlans(ctx context.Context, includeDeleted bool) ([]Plan, error) {
	rows, err := q.db.Query(ctx, listPlans, includeDeleted)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Plan
	for rows.Next() {
		var i Plan
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Amount,
			&i.Currency,
			&i.Interval,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeletePlan = `-- name: SoftDeletePlan :execrows
UPDATE plans SET deleted_at = now() WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeletePlan(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, softDeletePlan, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updatePlan = `-- name: UpdatePlan :one
UPDATE plans SET
    name     = COALESCE($1, name),
    amount   = COALESCE($2, amount),
    currency = COALESCE($3, currency),
    interval = COALESCE($4, interval)
WHERE id = $5 AND deleted_at IS NULL
RETURNING id, tenant_id, name, amount, currency, interval, deleted_at, created_at, updated_at
`

type UpdatePlanParams struct {
	Name     *string   `json:"name"`
	Amount   *int64    `json:"amount"`
	Currency *string   `json:"currency"`
	Interval *string   `json:"interval"`
	ID       uuid.UUID `json:"id"`
}

func (q *Queries) UpdatePlan(ctx context.Context, arg UpdatePlanParams) (Plan, error) {
	row := q.db.QueryRow(ctx, updatePlan,
		arg.Name,
		arg.Amount,
		arg.Currency,
		arg.Interval,
		arg.ID,
	)
	var i Plan
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Amount,
		&i.Currency,
		&i.Interval,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
