// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: portal.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const consumePortalToken = `-- name: ConsumePortalToken :execrows
UPDATE portal_access_tokens SET used_at = now()
WHERE token_hash = $1 AND used_at IS NULL AND expires_at > now()
`

func (q *Queries) ConsumePortalToken(ctx context.Context, tokenHash string) (int64, error) {
	result, err := q.db.Exec(ctx, consumePortalToken, tokenHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createPortalToken = `-- name: CreatePortalToken :one
INSERT INTO portal_access_tokens (tenant_id, customer_id, token_hash, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING id, tenant_id, customer_id, token_hash, expires_at, used_at, created_at
`

type CreatePortalTokenParams struct {
	TenantID   uuid.UUID `json:"tenant_id"`
	CustomerID uuid.UUID `json:"customer_id"`
	TokenHash  string    `json:"token_hash"`
	ExpiresAt  time.Time `json:"expires_at"`
}

func (q *Queries) CreatePortalToken(ctx context.Context, arg CreatePortalTokenParams) (PortalAccessToken, error) {
	row := q.db.QueryRow(ctx, createPortalToken,
		arg.TenantID,
		arg.CustomerID,
		arg.TokenHash,
		arg.ExpiresAt,
	)
	var i PortalAccessToken
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CustomerID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getPortalTokenByHash = `-- name: GetPortalTokenByHash :one
SELECT id, tenant_id, customer_id, token_hash, expires_at, used_at, created_at FROM portal_access_tokens WHERE token_hash = $1
`

// Resolve + consume a magic-link token. Runs on the admin pool (pre-session).
func (q *Queries) GetPortalTokenByHash(ctx context.Context, tokenHash string) (PortalAccessToken, error) {
	row := q.db.QueryRow(ctx, getPortalTokenByHash, tokenHash)
	var i PortalAccessToken
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CustomerID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}
