// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: processed_events.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertProcessedEvent = `-- name: InsertProcessedEvent :one
INSERT INTO processed_events (request_id, consumer, status)
VALUES ($1, $2, 'processing')
ON CONFLICT (request_id, consumer) DO NOTHING
RETURNING request_id, consumer, status, result, created_at, processed_at
`

type InsertProcessedEventParams struct {
	RequestID string `json:"request_id"`
	Consumer  string `json:"consumer"`
}

// InsertProcessedEvent inserts a new processing record for (request_id, consumer).
// Returns (row, nil) when the insert wins the race; returns (zero, pgx.ErrNoRows)
// when a record already exists — callers treat ErrNoRows as "already claimed".
func (q *Queries) InsertProcessedEvent(ctx context.Context, arg InsertProcessedEventParams) (ProcessedEvent, error) {
	row := q.db.QueryRow(ctx, insertProcessedEvent, arg.RequestID, arg.Consumer)
	var i ProcessedEvent
	err := row.Scan(
		&i.RequestID,
		&i.Consumer,
		&i.Status,
		&i.Result,
		&i.CreatedAt,
		&i.ProcessedAt,
	)
	return i, err
}

const getProcessedEvent = `-- name: GetProcessedEvent :one
SELECT request_id, consumer, status, result, created_at, processed_at
FROM processed_events
WHERE request_id = $1
  AND consumer   = $2
`

type GetProcessedEventParams struct {
	RequestID string `json:"request_id"`
	Consumer  string `json:"consumer"`
}

func (q *Queries) GetProcessedEvent(ctx context.Context, arg GetProcessedEventParams) (ProcessedEvent, error) {
	row := q.db.QueryRow(ctx, getProcessedEvent, arg.RequestID, arg.Consumer)
	var i ProcessedEvent
	err := row.Scan(
		&i.RequestID,
		&i.Consumer,
		&i.Status,
		&i.Result,
		&i.CreatedAt,
		&i.ProcessedAt,
	)
	return i, err
}

const markProcessedEventDone = `-- name: MarkProcessedEventDone :exec
UPDATE processed_events
SET status       = 'done',
    processed_at = now()
WHERE request_id = $1
  AND consumer   = $2
`

type MarkProcessedEventDoneParams struct {
	RequestID string `json:"request_id"`
	Consumer  string `json:"consumer"`
}

func (q *Queries) MarkProcessedEventDone(ctx context.Context, arg MarkProcessedEventDoneParams) error {
	_, err := q.db.Exec(ctx, markProcessedEventDone, arg.RequestID, arg.Consumer)
	return err
}

const markProcessedEventFailed = `-- name: MarkProcessedEventFailed :exec
UPDATE processed_events
SET status       = 'failed',
    processed_at = now()
WHERE request_id = $1
  AND consumer   = $2
`

type MarkProcessedEventFailedParams struct {
	RequestID string `json:"request_id"`
	Consumer  string `json:"consumer"`
}

func (q *Queries) MarkProcessedEventFailed(ctx context.Context, arg MarkProcessedEventFailedParams) error {
	_, err := q.db.Exec(ctx, markProcessedEventFailed, arg.RequestID, arg.Consumer)
	return err
}

// Ensure ProcessedEvent uses time package — pin the import so it is never dropped.
var _ = time.Time{}
var _ = pgtype.Timestamptz{}
