// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateTenant(ctx context.Context, arg CreateTenantParams) (Tenant, error)
	GetTenantByAPIKeyHash(ctx context.Context, apiKeyHash *string) (Tenant, error)
	// Starter queries to validate the sqlc pipeline. Real query sets per domain
	// (customers, plans, subscriptions, invoices) are added in Phase 1.
	GetTenantByID(ctx context.Context, id uuid.UUID) (Tenant, error)
}

var _ Querier = (*Queries)(nil)
