// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// Stamps the billing period forward by one interval (month or year) and
	// transitions status to 'active'. Called by the subscription_state handler
	// when a payment.succeeded event confirms a funded renewal.
	// new_period_start and new_period_end are computed in Go from the plan interval.
	AdvanceSubscriptionPeriod(ctx context.Context, arg AdvanceSubscriptionPeriodParams) (Subscription, error)
	CancelSubscription(ctx context.Context, arg CancelSubscriptionParams) (Subscription, error)
	ConsumePortalToken(ctx context.Context, tokenHash string) (int64, error)
	CountActiveSubscriptions(ctx context.Context) (int64, error)
	CountFailedInvoices(ctx context.Context) (int64, error)
	CountPaymentsToday(ctx context.Context) (int64, error)
	CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (ApiKey, error)
	CreateCustomer(ctx context.Context, arg CreateCustomerParams) (Customer, error)
	// Inserts an immutable invoice header. Status starts as 'open'.
	// amount is in kobo (minor units). period_start/period_end use the subscription
	// billing window so the invoice is human-readable for proration display.
	CreateInvoice(ctx context.Context, arg CreateInvoiceParams) (Invoice, error)
	// Inserts a single line item linked to an invoice.
	// amount may be negative (proration credit).
	CreateInvoiceItem(ctx context.Context, arg CreateInvoiceItemParams) (InvoiceItem, error)
	CreatePlan(ctx context.Context, arg CreatePlanParams) (Plan, error)
	CreatePortalToken(ctx context.Context, arg CreatePortalTokenParams) (PortalAccessToken, error)
	CreateSubscription(ctx context.Context, arg CreateSubscriptionParams) (Subscription, error)
	CreateTenant(ctx context.Context, arg CreateTenantParams) (Tenant, error)
	// Resolve a bearer key to its tenant. Runs on the admin pool (pre-tenant-scope).
	GetAPIKeyByHash(ctx context.Context, keyHash string) (ApiKey, error)
	GetCustomer(ctx context.Context, id uuid.UUID) (Customer, error)
	GetCustomerByEmail(ctx context.Context, email string) (Customer, error)
	GetInvoice(ctx context.Context, id uuid.UUID) (Invoice, error)
	// Looks up the most recent 'open' invoice for a subscription. Used by the
	// invoicing handler to implement create-or-find semantics so a redelivered
	// payment.succeeded event updates the existing invoice rather than creating
	// a duplicate. (Idempotency at the insert level is handled by the wrapper;
	// this query guards against the edge-case where the handler runs twice
	// within the same idempotency window due to a crash-after-commit.)
	GetOpenInvoiceBySubscription(ctx context.Context, subscriptionID pgtype.UUID) (Invoice, error)
	// Finds a paid invoice by its Nomba transaction reference.
	GetPaidInvoiceByNombaReference(ctx context.Context, nombaReference *string) (Invoice, error)
	GetPlan(ctx context.Context, id uuid.UUID) (Plan, error)
	// Resolve + consume a magic-link token. Runs on the admin pool (pre-session).
	GetPortalTokenByHash(ctx context.Context, tokenHash string) (PortalAccessToken, error)
	// Fetch the current record for (request_id, consumer). Used by the idempotency
	// wrapper to check whether a previous run already completed successfully.
	GetProcessedEvent(ctx context.Context, arg GetProcessedEventParams) (ProcessedEvent, error)
	GetSubscription(ctx context.Context, id uuid.UUID) (Subscription, error)
	GetSubscriptionByCustomer(ctx context.Context, customerID uuid.UUID) (Subscription, error)
	GetTenantByEmail(ctx context.Context, email string) (Tenant, error)
	// Auth lookups run on the admin pool (pre-session, RLS-bypassing); everything else
	// runs tenant-scoped via WithTenant.
	GetTenantByID(ctx context.Context, id uuid.UUID) (Tenant, error)
	// Try to claim processing rights for (request_id, consumer). Returns the newly
	// inserted row on success, or nothing on conflict (event already claimed).
	// ON CONFLICT DO NOTHING means the INSERT is a no-op when the pair already exists;
	// the caller must check whether a row was actually inserted (rowsAffected == 1).
	InsertProcessedEvent(ctx context.Context, arg InsertProcessedEventParams) (ProcessedEvent, error)
	ListAPIKeys(ctx context.Context) ([]ApiKey, error)
	ListCustomers(ctx context.Context, arg ListCustomersParams) ([]Customer, error)
	// Returns all active subscriptions whose current billing period has elapsed.
	// The scheduler sweeps these on each tick and publishes a subscription.renew
	// event for each one so the subscription_state handler can charge the card.
	ListDueSubscriptions(ctx context.Context) ([]Subscription, error)
	ListInvoiceItems(ctx context.Context, invoiceID uuid.UUID) ([]InvoiceItem, error)
	ListInvoicesByCustomer(ctx context.Context, customerID uuid.UUID) ([]Invoice, error)
	ListPlans(ctx context.Context, includeDeleted bool) ([]Plan, error)
	// Transitions an invoice from 'open' → 'paid' and records the Nomba
	// transaction reference. Returns the updated row so callers can confirm.
	MarkInvoicePaid(ctx context.Context, arg MarkInvoicePaidParams) (Invoice, error)
	// Reverts a paid invoice back to 'open' when a payment reversal occurs.
	MarkInvoiceUnpaid(ctx context.Context, id uuid.UUID) (Invoice, error)
	// Stamp the record as done after the handler commits successfully.
	MarkProcessedEventDone(ctx context.Context, arg MarkProcessedEventDoneParams) error
	// Stamp the record as failed so operators can query and alert on stuck events.
	MarkProcessedEventFailed(ctx context.Context, arg MarkProcessedEventFailedParams) error
	RevenueSeries(ctx context.Context) ([]RevenueSeriesRow, error)
	RevokeAPIKey(ctx context.Context, id uuid.UUID) (int64, error)
	SetCustomerCardToken(ctx context.Context, arg SetCustomerCardTokenParams) (Customer, error)
	// General-purpose status writer used by the subscription_state handler for
	// past_due and unpaid transitions when a payment fails.
	SetSubscriptionStatus(ctx context.Context, arg SetSubscriptionStatusParams) (Subscription, error)
	SoftDeletePlan(ctx context.Context, id uuid.UUID) (int64, error)
	// Monthly recurring revenue: normalize yearly plans to a monthly figure (minor units).
	SumMRR(ctx context.Context) (int64, error)
	TouchAPIKey(ctx context.Context, id uuid.UUID) error
	UpdateCustomer(ctx context.Context, arg UpdateCustomerParams) (Customer, error)
	UpdatePlan(ctx context.Context, arg UpdatePlanParams) (Plan, error)
	UpdateTenantSettings(ctx context.Context, arg UpdateTenantSettingsParams) (Tenant, error)
}

var _ Querier = (*Queries)(nil)
