// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: subscriptions.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const cancelSubscription = `-- name: CancelSubscription :one
UPDATE subscriptions SET
    cancel_at_period_end = $1,
    status               = CASE WHEN $1 THEN status ELSE 'canceled' END,
    canceled_at          = CASE WHEN $1 THEN canceled_at ELSE now() END
WHERE id = $2
RETURNING id, tenant_id, customer_id, plan_id, status, current_period_start, current_period_end, cancel_at_period_end, canceled_at, created_at, updated_at
`

type CancelSubscriptionParams struct {
	AtPeriodEnd bool      `json:"at_period_end"`
	ID          uuid.UUID `json:"id"`
}

func (q *Queries) CancelSubscription(ctx context.Context, arg CancelSubscriptionParams) (Subscription, error) {
	row := q.db.QueryRow(ctx, cancelSubscription, arg.AtPeriodEnd, arg.ID)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CustomerID,
		&i.PlanID,
		&i.Status,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.CancelAtPeriodEnd,
		&i.CanceledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSubscription = `-- name: CreateSubscription :one
INSERT INTO subscriptions (tenant_id, customer_id, plan_id, status)
VALUES ($1, $2, $3, 'incomplete')
RETURNING id, tenant_id, customer_id, plan_id, status, current_period_start, current_period_end, cancel_at_period_end, canceled_at, created_at, updated_at
`

type CreateSubscriptionParams struct {
	TenantID   uuid.UUID `json:"tenant_id"`
	CustomerID uuid.UUID `json:"customer_id"`
	PlanID     uuid.UUID `json:"plan_id"`
}

func (q *Queries) CreateSubscription(ctx context.Context, arg CreateSubscriptionParams) (Subscription, error) {
	row := q.db.QueryRow(ctx, createSubscription, arg.TenantID, arg.CustomerID, arg.PlanID)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CustomerID,
		&i.PlanID,
		&i.Status,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.CancelAtPeriodEnd,
		&i.CanceledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSubscription = `-- name: GetSubscription :one
SELECT id, tenant_id, customer_id, plan_id, status, current_period_start, current_period_end, cancel_at_period_end, canceled_at, created_at, updated_at FROM subscriptions WHERE id = $1
`

func (q *Queries) GetSubscription(ctx context.Context, id uuid.UUID) (Subscription, error) {
	row := q.db.QueryRow(ctx, getSubscription, id)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CustomerID,
		&i.PlanID,
		&i.Status,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.CancelAtPeriodEnd,
		&i.CanceledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSubscriptionByCustomer = `-- name: GetSubscriptionByCustomer :one
SELECT id, tenant_id, customer_id, plan_id, status, current_period_start, current_period_end, cancel_at_period_end, canceled_at, created_at, updated_at FROM subscriptions
WHERE customer_id = $1
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetSubscriptionByCustomer(ctx context.Context, customerID uuid.UUID) (Subscription, error) {
	row := q.db.QueryRow(ctx, getSubscriptionByCustomer, customerID)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CustomerID,
		&i.PlanID,
		&i.Status,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.CancelAtPeriodEnd,
		&i.CanceledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
