// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tenants.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createTenant = `-- name: CreateTenant :one
INSERT INTO tenants (name, email, nomba_account_id, nomba_client_id, nomba_client_secret, api_key_hash)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, name, email, nomba_account_id, nomba_client_id, nomba_client_secret, api_key_hash, created_at, updated_at
`

type CreateTenantParams struct {
	Name              string  `json:"name"`
	Email             string  `json:"email"`
	NombaAccountID    *string `json:"nomba_account_id"`
	NombaClientID     *string `json:"nomba_client_id"`
	NombaClientSecret *string `json:"nomba_client_secret"`
	ApiKeyHash        *string `json:"api_key_hash"`
}

func (q *Queries) CreateTenant(ctx context.Context, arg CreateTenantParams) (Tenant, error) {
	row := q.db.QueryRow(ctx, createTenant,
		arg.Name,
		arg.Email,
		arg.NombaAccountID,
		arg.NombaClientID,
		arg.NombaClientSecret,
		arg.ApiKeyHash,
	)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.NombaAccountID,
		&i.NombaClientID,
		&i.NombaClientSecret,
		&i.ApiKeyHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTenantByAPIKeyHash = `-- name: GetTenantByAPIKeyHash :one
SELECT id, name, email, nomba_account_id, nomba_client_id, nomba_client_secret, api_key_hash, created_at, updated_at FROM tenants WHERE api_key_hash = $1
`

func (q *Queries) GetTenantByAPIKeyHash(ctx context.Context, apiKeyHash *string) (Tenant, error) {
	row := q.db.QueryRow(ctx, getTenantByAPIKeyHash, apiKeyHash)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.NombaAccountID,
		&i.NombaClientID,
		&i.NombaClientSecret,
		&i.ApiKeyHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTenantByID = `-- name: GetTenantByID :one

SELECT id, name, email, nomba_account_id, nomba_client_id, nomba_client_secret, api_key_hash, created_at, updated_at FROM tenants WHERE id = $1
`

// Starter queries to validate the sqlc pipeline. Real query sets per domain
// (customers, plans, subscriptions, invoices) are added in Phase 1.
func (q *Queries) GetTenantByID(ctx context.Context, id uuid.UUID) (Tenant, error) {
	row := q.db.QueryRow(ctx, getTenantByID, id)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.NombaAccountID,
		&i.NombaClientID,
		&i.NombaClientSecret,
		&i.ApiKeyHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
